const routes = {
    main: '/',
    stories: '/stories',
    storyDetails: '/stories/details',
    posts: '/posts',
    postDetails: '/posts/details',
    vaccinations: '/vaccinations',
    vaccinationDetails: '/vaccinations/details',
    advices: '/advices',
    support: '/support',
    supportMessages: '/support/messages',
    faq: '/faq',
    faqDetails: '/faq/details',
    users: '/users',
    userDetails: '/users/details',
    auth: '/auth',
    setPassword: '/auth/set-password',
    references: '/references',
    referencesDiseases: '/references/diseases',
    referencesDiseaseDetails: '/references/diseases/details',
    referencesActivities: '/references/activities',
    referencesHobbies: '/references/hobbies',
    referencesRegions: '/references/regions',
    referencesRegionDetails: '/references/regions/details',
    referencesCountries: '/references/countries',
    referencesCountryDetails: '/references/countries/details',
    referencesSupportTopics: '/references/support-topics',
    referencesDocuments: '/references/documents',
    referencesDocumentDetails: '/references/documents/details',
    resetPassword: '/profile/reset-password',
    about: '/about'
}

export default routes
