name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
      version:
        description: Version
        required: true

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version || github.event.release.tag_name }}
      - name: Fetch @action/get-parameters
        uses: actions/checkout@v2
        with:
          repository: redmadrobot-tomsk/action-get-parameters
          ref: refs/tags/v1.1.1
          token: ${{ secrets.CI_PAT }}
          path: .github/actions/get-parameters
      - name: Fetch parameters
        uses: ./.github/actions/get-parameters
        with:
          token: ${{ secrets.CI_PAT }}
          key: ${{ secrets.ACTION_KEY }}
          env_file: .env
      - run: |
          VERSION=$(cat VERSION)
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          echo "CONTAINER_IMAGE=ghcr.io/redmadrobot-tomsk/mik-front-admin:${VERSION}-${{ env.ENVIRONMENT }}" >> ${GITHUB_ENV}
          cat > config.js <<EOF
          module.exports = {
              service_url: '${{ env.API_URL }}',
              env: 'production',
              sentry_env: '${{ env.ENVIRONMENT }}'
          };
          EOF
          echo
          echo "Application config:"
          cat config.js
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: github-actions
          password: ${{ secrets.CI_PAT }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Fetch @action/kubectl
        uses: actions/checkout@v2
        with:
          repository: redmadrobot-tomsk/action-kubectl
          ref: refs/tags/v1.5.3
          token: ${{ secrets.CI_PAT }}
          path: .github/actions/kubectl
      - name: Deploy project
        uses: ./.github/actions/kubectl
        with:
          kubeconfig: ${{ env.KUBERNETES_CONFIG }}
          action: apply
          manifest: kubernetes.yaml
      - name: Deploy ingress
        uses: ./.github/actions/kubectl
        with:
          kubeconfig: ${{ env.KUBERNETES_CONFIG }}
          action: apply
          manifest: ingress.${{ env.ENVIRONMENT }}.yaml
